version: '3.1'

services:
  drupal:
    image: custom-drupal
    build: .
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always
  
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - drupal-data:/var/lib/postgresql/data
    restart: always

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites: